# - Entfernen von Reihen ohne Produktnamen
# - Hinzufügen der absoluten und relativen Sollwerte

## Einlesen der Daten

In [1]:
import pandas as pd
import numpy as np
import csv

In [2]:
# Daten einlesen
df=pd.read_csv("process_data_df10.csv", header=[0,1], na_values=['nan'],
sep=',',low_memory=False)

# Spalte ohne Information löschen
df2=df.drop(['Unnamed: 0_level_0'],axis=1)


df2.head()

/home/alpha/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py:3946: PerformanceWarning: dropping on a non-lexsorted multi-index without a level parameter may impact performance.
  new_axis = axis.drop(labels, errors=errors)

             ps                                                             \
             ps    ps_datum ps_beschichtete_rollenlange_m ps_c_losung_wt_%
0  cb031d4b18ff  2018-05-13                        4487.0             31.0
1  cb031d4b18ff  2018-05-13                        4487.0             31.0
2  cb031d4b18ff  2018-05-13                        4487.0             31.0
3  cb031d4b18ff  2018-05-13                        4487.0             31.0
4  cb031d4b18ff  2018-05-13                        4487.0             31.0

                                                                       \
  ps_gap_micro_m ps_dicke_as_micro_m ps_dicke_1 ps_dicke_2 ps_dicke_3
0          250.0               136.0      136.0      134.0      134.0
1          250.0               136.0      136.0      134.0      134.0
2          250.0               136.0      136.0      134.0      134.0
3          250.0               136.0      136.0      134.0      134.0
4          250.0               136.0      136.0      134.0      134.0

              ...             qc                                              \
  ps_dicke_4  ... p_product_type p_product_size p_effective_area_per_leaf_m2
0      135.0  ...   6989995295da              8                       1.4646
1      135.0  ...   6989995295da              8                       1.4646
2      135.0  ...   6989995295da              8                       1.4646
3      135.0  ...   6989995295da              8                       1.4646
4      135.0  ...   6989995295da              8                       1.4646

                                                                 \
  p_effective_pressure_bar qc_flux_l/m2/h qc_a-value_l/m2/h/bar
0                     8.71      40.286235              4.625285
1                     8.71      40.252401              4.621401
2                     8.71      39.718186              4.560067
3                     8.71      39.441426              4.528292
4                     8.71      39.731817              4.561632


  qc_b-value_m/s_10-6 qc_flux_m3/m2/day sum_of_scrap roll_position
0            3.678446          0.966870          0.0     58.181818
1            3.165247          0.966058          0.0    116.363636
2            3.170593          0.953236          0.0    174.545455
3            2.855092          0.946594          0.0    232.727273
4            2.810373          0.953564          0.0    290.909091

[5 rows x 343 columns]

## 1. Entfernen von Reihen ohne Produktnamen

In [3]:
# Zu Beginn alle im DataFrame vorkommenden Produktnamen auslesen
produktnamen=list(df2['qc']['p_product_full_name'])

In [4]:
# Erzeugen eines Arrays, in welches die Sollwerte gemäß Herstellerangaben eingetragen werden
sollwerte=np.zeros((118687,2))

In [5]:
# Info zu df2 vor dem Bereinigen
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 118687 entries, 0 to 118686
Columns: 343 entries, (ps, ps) to (qc, roll_position)
dtypes: bool(7), float64(296), int64(4), object(36)
memory usage: 305.0+ MB

In [6]:
# Produktnamen laut Herstellerangaben
# Stimmt der Produktname überein, werden die Sollwerte für den Salrückhalt (linke Spalte) und den Permatdurchsatz (rechte Spalte) eingetragen
# leere Spalten werden in der else-Bedingung aussortiert

for i in range(len(produktnamen)):
    if produktnamen[i]=='a79cf6a73839':
        sollwerte[i]=[99.8, 5.2]
        
    elif produktnamen[i]=='c807697b3c7e':
        sollwerte[i]=[99.8, 24.6]
        
    elif produktnamen[i]=='f22a7fef71c5':
        sollwerte[i]=[99.8, 27.3] 
        
    elif produktnamen[i]=='c13b2f69d3c1':
        sollwerte[i]=[99.8, 7.2]  
        
    elif produktnamen[i]=='3e94b7067349':
        sollwerte[i]=[99.8, 34.1]  
        
    elif produktnamen[i]=='3394d82edc97':
        sollwerte[i]=[99.8, 37.5]  
        
    elif produktnamen[i]=='df9e75b29918':
        sollwerte[i]=[99.7, 39.9]  
        
    elif produktnamen[i]=='316c8d1ffca1':
        sollwerte[i]=[99.5, 43.9]  
        
    elif produktnamen[i]=='5661014763c8':
        sollwerte[i]=[99.5, 8.9]  
        
    elif produktnamen[i]=='73928f2577b5':
        sollwerte[i]=[99.7, 39.9]  
        
    elif produktnamen[i]=='22227b31350f':
        sollwerte[i]=[99.5, 41.5]  
        
    elif produktnamen[i]=='df1d09e643af':
        sollwerte[i]=[99.7, 8.9]  
        
    elif produktnamen[i]=='e2b1e6e1d5f5':
        sollwerte[i]=[99.7, 37.9]  
        
    elif produktnamen[i]=='54b98d0fe2eb':
        sollwerte[i]=[99.5, 41.7]
        
    elif produktnamen[i]=='ff16223eb2bf':
        sollwerte[i]=[99.5, 39.9]
        
    elif produktnamen[i]=='0cc0ba87b12f':
        sollwerte[i]=[99.5, 7.4]        
        
    elif produktnamen[i]=='a640f68db89c':
        sollwerte[i]=[99.5, 34.8]        
        
    elif produktnamen[i]=='b3ccc5e5f9b5':
        sollwerte[i]=[99.5, 36.2]        
        
    elif produktnamen[i]=='2256f65c362b':
        sollwerte[i]=[99.5, 38.3]        
        
    elif produktnamen[i]=='33d21930e431':
        sollwerte[i]=[99.5, 8.2]        
        
    elif produktnamen[i]=='3a0c28c7fc8c':
        sollwerte[i]=[99.5, 38.6]                
        
    elif produktnamen[i]=='630448a85ca3':
        sollwerte[i]=[99.5, 42.6]
    else:
        print(i)
        df2=df2.drop(df2.index[i])

9723
11598
15501
17752
32413
39389
49116
55882
68301
68491
77866
80634
88800
99333
101312
115985
117371

In [7]:
# Info zu df2 nach dem Bereinigen
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 118670 entries, 0 to 118686
Columns: 343 entries, (ps, ps) to (qc, roll_position)
dtypes: bool(7), float64(296), int64(4), object(36)
memory usage: 305.9+ MB

## 2.Hinzufügen der absoluten und relativen Sollwerte

In [8]:
# Erzeugen eines Backups
sollwerte_b=np.copy(sollwerte)
sollwerte_b

array([[99.5, 36.2],
       [99.5, 36.2],
       [99.5, 36.2],
       ...,
       [99.5, 36.2],
       [99.5, 36.2],
       [99.5, 36.2]])

In [9]:
# Sollwerte als Array auslesen:
# sollwerte2=Salrückhalt
# sollwerte3=Permatdurchfluss
sollwerte2=sollwerte_b[:,0]
sollwerte3=sollwerte_b[:,1]

In [10]:
# Typvereinfachung -> Teilen einer Liste durch eine Liste (später)
sollwerte_salzr=sollwerte2.tolist()
sollwerte_durchf=sollwerte3.tolist()

In [11]:
# Erneut Überprüfen, ob keine leeren Einträge vorhanden sind
sollwerte_salzr=list(filter(lambda a: a!=0, sollwerte_salzr))
sollwerte_durchf=list(filter(lambda a: a!=0, sollwerte_durchf))

In [12]:
# istwerte als Liste auslesen
ist_salzr=df2['qc']['qc_salzrckhalt']
ist_durchf=df2['qc']['qc_durchfluss']

In [13]:
# relative Abweichung berechnen

Abw_salzr=np.absolute(sollwerte_salzr-ist_salzr)/sollwerte_salzr*100
Abw_durchf=np.absolute(sollwerte_durchf-ist_durchf)/sollwerte_durchf*100

In [14]:
# Hinzufügen der Sollwerte zum DataFrame

df2['Sollwerte','soll_salzr_abs']=sollwerte_salzr
df2['Sollwerte','soll_permeatd_abs']=sollwerte_durchf
df2['Sollwerte', 'soll_salzr_rel']=Abw_salzr
df2['Sollwerte', 'soll_permeatd_rel']=Abw_durchf

In [15]:
df2.head()

             ps                                                             \
             ps    ps_datum ps_beschichtete_rollenlange_m ps_c_losung_wt_%
0  cb031d4b18ff  2018-05-13                        4487.0             31.0
1  cb031d4b18ff  2018-05-13                        4487.0             31.0
2  cb031d4b18ff  2018-05-13                        4487.0             31.0
3  cb031d4b18ff  2018-05-13                        4487.0             31.0
4  cb031d4b18ff  2018-05-13                        4487.0             31.0

                                                                       \
  ps_gap_micro_m ps_dicke_as_micro_m ps_dicke_1 ps_dicke_2 ps_dicke_3
0          250.0               136.0      136.0      134.0      134.0
1          250.0               136.0      136.0      134.0      134.0
2          250.0               136.0      136.0      134.0      134.0
3          250.0               136.0      136.0      134.0      134.0
4          250.0               136.0      136.0      134.0      134.0

              ...             qc                                            \
  ps_dicke_4  ... qc_flux_l/m2/h qc_a-value_l/m2/h/bar qc_b-value_m/s_10-6
0      135.0  ...      40.286235              4.625285            3.678446
1      135.0  ...      40.252401              4.621401            3.165247
2      135.0  ...      39.718186              4.560067            3.170593
3      135.0  ...      39.441426              4.528292            2.855092
4      135.0  ...      39.731817              4.561632            2.810373

                                                    Sollwerte  \
  qc_flux_m3/m2/day sum_of_scrap roll_position soll_salzr_abs
0          0.966870          0.0     58.181818           99.5
1          0.966058          0.0    116.363636           99.5
2          0.953236          0.0    174.545455           99.5
3          0.946594          0.0    232.727273           99.5
4          0.953564          0.0    290.909091           99.5


  soll_permeatd_abs soll_salzr_rel soll_permeatd_rel
0              36.2       0.045087          1.707208
1              36.2       0.030558          1.621790
2              36.2       0.023437          0.273103
3              36.2       0.067889          0.425610
4              36.2       0.077781          0.307515

[5 rows x 347 columns]

In [16]:
df2['Sollwerte']

        soll_salzr_abs  soll_permeatd_abs  soll_salzr_rel  soll_permeatd_rel
0                 99.5               36.2        0.045087           1.707208
1                 99.5               36.2        0.030558           1.621790
2                 99.5               36.2        0.023437           0.273103
3                 99.5               36.2        0.067889           0.425610
4                 99.5               36.2        0.077781           0.307515
...                ...                ...             ...                ...
118682            99.5               36.2        0.095594           8.737486
118683            99.5               36.2        0.047043          10.007924
118684            99.5               36.2        0.092809          11.920763
118685            99.5               36.2        0.015256           4.767057
118686            99.5               36.2        0.049864           4.106214

[118670 rows x 4 columns]

## 3. Speichern als .csv

In [17]:
df2.to_csv('process_data_df11.csv')